# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb743b6f0a4de6d1d3ab576e21f0934679a04b874715d5250e81a5ec5660f230e12445f59809fe09af40b15b73a97887d59b8d76bf6c3eb261b72bf2c06b8824

test:
  secret_key_base: 8ad4be795d450608a8d06860334b0a948fe01c194822c945994136518ef2a9ddd2a8cec2477620573a0f6418d1ad980c174f3aee9c159bcae1e3f33c167cbf45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
